theme: jekyll-theme-slate
title: Treinamento VBA - Módulo Avançado
description: O treinamento visa um público que já tenha tido contato com a linguagem, neste módulo é apresentado meios de se comunicar com equipamentos, integrar com outros softwares e programar em módulos de classes. 
