theme: jekyll-theme-slate
title: Treinamento VBA - Módulo Básico
description: O treinamento visa um público que não tido contato com a ferramenta ou um contato muito pequeno, neste módulo são apresentados os conceitos básicos da linguagem e apresentado todo o ambiente de desenvolvimento.
